In [2]:
from mxnet import gluon, nd
from mxnet.gluon import nn

class CenteredLayer(nn.Block):
    def __init__(self, **kwargs):
        super(CenteredLayer, self).__init__(**kwargs)
        
    def forward(self, x):
        return x - x.mean()

In [3]:
layer = CenteredLayer()
layer(nd.array([1, 2, 3, 4, 5]))


[-2. -1.  0.  1.  2.]
<NDArray 5 @cpu(0)>

In [5]:
net = nn.Sequential()
net.add(nn.Dense(128),
       CenteredLayer())

In [7]:
net.initialize()
y = net(nd.random.uniform(shape=(4, 8)))
y.mean().asscalar()

-6.0936145e-10

In [11]:
params = gluon.ParameterDict()
params.get('param2', shape=(2, 3))
params

(
  Parameter param2 (shape=(2, 3), dtype=<class 'numpy.float32'>)
)

In [14]:
class MyDense(nn.Block):
    def __init__(self, units, in_units, **kwargs):
        super(MyDense, self).__init__(**kwargs)
        self.weight = self.params.get('weight', shape=(in_units, units))
        self.bias = self.params.get('bias', shape=(units,))
        
    def forward(self, x):
        linear = nd.dot(x, self.weight.data()) + self.bias.data()
        return nd.relu(linear)

In [16]:
dense = MyDense(units=3, in_units=5)
dense.params

mydense2_ (
  Parameter mydense2_weight (shape=(5, 3), dtype=<class 'numpy.float32'>)
  Parameter mydense2_bias (shape=(3,), dtype=<class 'numpy.float32'>)
)

In [18]:
dense.initialize()
dense(nd.random.uniform(shape=(2, 5)))


[[0.06917784 0.01627153 0.01029644]
 [0.02602214 0.04537309 0.        ]]
<NDArray 2x3 @cpu(0)>

In [19]:
net = nn.Sequential()
net.add(MyDense(8, in_units=64),
       MyDense(1, in_units=8))
net.initialize()
net(nd.random.uniform(shape=(2, 64)))


[[0.03820475]
 [0.04035058]]
<NDArray 2x1 @cpu(0)>

In [30]:
net = nn.Sequential()
net.add(MyDense(10, in_units=100),
      MyDense(4, in_units=10))
net.initialize()
net(nd.random.uniform(shape=(4, 100)))


[[0.         0.02280167 0.         0.04409103]
 [0.         0.00430965 0.         0.03510828]
 [0.01843599 0.01175718 0.         0.02947279]
 [0.         0.01619794 0.         0.02685324]]
<NDArray 4x4 @cpu(0)>